setxkbmap q6 &
xset r rate 330 45 &
xrdb ~/.Xresources

exec xsetroot -cursor_name left_ptr &
exec unclutter -idle 5 -root &
#exec feh --bg-center ~/img/thearcher1680x1050.png &

exec i3 -V &> /home/daethorian/.logs/i3.log
