km &
xset r rate 330 45 &
xset -b
xrdb ~/.Xresources

exec nm-applet &
exec xsetroot -cursor_name left_ptr &
exec unclutter -idle 1 -root &
exec keynav &
wp &
gnome-keyring --start &


# exec i3 -V &> $HOME/.logs/i3.log
exec herbstluftwm --locked &> $HOME/.logs/hlwm.log
