c=()
if [[ $TCOLORS = 256 ]]; then
    c+="%F{237}"       # 1.  Prompt decoration
    c+="%F{143}"       # 2.  Hostname
    c+="%F{160}"       # 3.  Hostname root
    c+="%F{067}"       # 4.  Directory
    c+="%F{096}"       # 5.  Directory non-multi
    c+="%F{196}"       # 6.  Error
    c+="%F{184}"       # 7.  Jobs
    c+="%F{067}"       # 8.  Clock
    c+="%F{195}"       # 9.  Mail
    c+="%F{062}"       # 10. Battery percent
    c+="%F{063}"       # 11. Battery timeleft
    c+="%F{196}"       # 12. TMOUT
    c+="%F{066}"       # 13. CVS System
    c+="%F{214}"       # 14. CVS Repo
    c+="%F{083}"       # 15. CVS Clean
    c+="%F{160}"       # 16. CVS Unstaged
    c+="%F{095}"       # 17. CVS Action
    c+="%F{202}"       # 18. CVS Staged / Debug
    c+="%F{120}"       # 19. Enabled / Success
    c+="%F{240}"       # 20. Disabled
    c+="%F{067}"       # 21. Doc: Function
    c+="%F{240}"       # 22. Doc: Undocumented
    c+="%F{148}"       # 23. Doc: File
    c+="%F{048}"       # 24. Comp: Descriptions
    c+="%F{067}"       # 25. Comp: Directories
    c+="%F{196}"       # 26. Comp: Corrections
    c+="%F{045}"       # 27. IP Adress
    c+="%F{123}"       # 28. CVS Super repo
else
    c+="%F{black}"     # 1.  Prompt decoration
    c+="%F{green}"     # 2.  Hostname
    c+="%F{red}"       # 3.  Hostname root
    c+="%F{blue}"      # 4.  Directory
    c+="%F{red}"       # 5.  Directory non-multi
    c+="%F{red}"       # 6.  Error
    c+="%F{yellow}"    # 7.  Jobs
    c+="%F{cyan}"      # 8.  Clock
    c+="%F{red}"       # 9.  Mail
    c+="%F{yellow}"    # 10. Battery percent
    c+="%F{magenta}"   # 11. Battery timeleft
    c+="%F{red}"       # 12. TMOUT
    c+="%F{yellow}"    # 13. CVS System
    c+="%F{yellow}"    # 14. CVS Repo
    c+="%F{green}"     # 15. CVS Clean
    c+="%F{red}"       # 16. CVS Unstaged
    c+="%F{cyan}"      # 17. CVS Action
    c+="%F{cyan}"      # 18. Debug
    c+="%F{green}"     # 19. Enabled / Success
    c+="%F{red}"       # 20. Disabled
    c+="%F{blue}"      # 21. Doc: Function
    c+="%F{white}"     # 22. Doc: Undocumented
    c+="%F{red}"       # 23. Doc: File
    c+="%F{green}"     # 24. Comp: Descriptions
    c+="%F{blue}"      # 25. Comp: Directories
    c+="%F{red}"       # 26. Comp: Corrections
    c+="%F{cyan}"      # 27. IP Adress
    c+="%F{cyan}"      # 28. CVS Super repo
fi

export c
