c=()
c+="0"     # 1.  Prompt decoration
c+="2"     # 2.  Hostname
c+="1"       # 3.  Hostname root
c+="4"      # 4.  Directory
c+="1"       # 5.  Directory non-multi
c+="1"       # 6.  Error
c+="3"    # 7.  Jobs
c+="6"      # 8.  Clock
c+="1"       # 9.  Mail
c+="3"    # 10. Battery percent
c+="5"   # 11. Battery timeleft
c+="1"       # 12. TMOUT
c+="3"    # 13. CVS System
c+="3"    # 14. CVS Repo
c+="2"     # 15. CVS Clean
c+="1"       # 16. CVS Unstaged
c+="9"      # 17. CVS Action
c+="6"      # 18. Debug
c+="2"     # 19. Enabled / Success
c+="1"       # 20. Disabled
c+="4"      # 21. Doc: Function
c+="8"     # 22. Doc: Undocumented
c+="1"       # 23. Doc: File
c+="2"     # 24. Comp: Descriptions
c+="4"      # 25. Comp: Directories
c+="1"       # 26. Comp: Corrections
c+="6"      # 27. IP Adress

export c
