#!/bin/zsh

if (( $+commands[qutebrowser])) ; then
    qutebrowser "$@"
elif (( $+commands[chromium] )) ; then
    chromium "$@"
elif (( $+commands[chromium-browser] )); then
    chromium-browser "$@"
fi
