#!/bin/zsh
# dmenu ssh tmux terminal spawner
# Written by Lowe Thiderman (lowe.thiderman@gmail.com)
# WTFPL

grep -Ei "^host " $HOME/.ssh/config | sed -r "s/host //i" \
    | dmenu_any - "urxvt -e ssh %q -t bin/mux main"
