#!/bin/zsh
# dmenu application launcher. Uses defaulted options.
# Written by Lowe Thiderman (lowe.thiderman@gmail.com)
# WTFPL

source $XDG_DATA_HOME/dmenu/dmenurc

/usr/bin/dmenu_run ${(z)DMENU_OPTIONS}
