#!/usr/bin/zsh

log=$HOME/.logs/emacs-daemon.log
notify-send -u low -t 3000 "Starting emacs..."

emacs --daemon &> $log &|

until tail -n 3 $log | grep -i "started" ; do
    sleep 0.5
done
notify-send -t 3000 "Emacs started."
