#!/usr/bin/env python

import subprocess as sub
import json
import sys


def get_data():
    j = sub.check_output(['i3-msg', '-t', 'get_tree'])
    return json.loads(j.decode())


def get_current():
    j = sub.check_output(['i3-msg', '-t', 'get_workspaces'])
    d = json.loads(j.decode())
    for ws in d:
        if ws['focused']:
            return ws['name']


def traverse(nodes, name):
    ret = []
    for node in nodes:
        if 'nodes' in node:
            for inner in traverse(node['nodes'], name):
                ret.append(inner)

        if node['name'] and name in node['name']:
            ret.append(node)

    return ret


def focus(node):
    sub.check_output(
        ['i3-msg', '[id="{0}"]'.format(node['window']), 'focus']
    )


def main(*args):
    current = get_current()
    workspaces = get_data()['nodes'][1]['nodes'][1]['nodes']
    for ws in workspaces:
        if ws['name'] == current:
            for node in traverse(ws['nodes'], args[0]):
                return focus(node)

if __name__ == '__main__':
    main(*sys.argv[1:])
