#!/usr/bin/env python

# Helper that either runs an i3 command or sends keystrokes to emacs
# depending on if emacs is focused or not.

import i3
import sys
from subprocess import call

f = i3.filter(focused=True)[0]
if f["window_properties"]["class"] == "Emacs":
    call(["xdotool", "key", "--window", str(f["window"]), sys.argv[2]])
else:
    i3.msg("command", sys.argv[1])
