#!/usr/bin/env python

import i3
import sys


def main():
    ws = sys.argv[1]
    f = i3.filter(name=ws)
    if len(f) == 0:
        print(0)
        sys.exit(0)

    f = f[0]
    if "nodes" in f:
        f = f["nodes"]
        if "nodes" in f:
            f = f["nodes"]
    print(len(f))


if __name__ == '__main__':
    main()
