#!/bin/zsh

f=$(readlink -f $1)
if [[ -f $f ]] && [[ -x $f ]] ; then
  if [[ -n "$2" ]] ; then
    local target=$2
  else
    local target=$(basename $1)
  fi

  if ! has $target ; then
    print -P "Installing %B${c[19]}$(basename $1)%f%b as %B${c[19]}${target}%f%b"
    ln -s $f $HOMEBIN/$target
  else
    echo "Error: $target is already installed"
  fi
else
  echo "Error: $(basename $f) is not an executable file"
fi
