#!/bin/zsh
# tmux session manager for smooth remote management.
# Written by Lowe Thiderman (lowe.thiderman@gmail.com)
# WTFPL

sess=${1:-main}
# Attach if it exists, create it if it doesn't.
if tmux ls | grep -E "^$sess:" &> /dev/null; then
    cmd="attach -d -t"
else
    cmd="new-session -s"
fi

# The LANG part is for letting tmux know that it actually can UTF8.
LANG="en_US.utf8" tmux ${(z)cmd} $sess
