#!/bin/zsh

tmux switch-client -t main
wmraise main@$HOST
tmux select-window -t $1
tmux select-pane -t 0

if [[ $1 = 2 ]]; then
  name="dev"
elif [[ $1 = 1 ]]; then
  name="irc"
fi

if [[ -n "$name" ]]; then
  tmux rename-window $name
fi
