#!/usr/bin/env zsh

source $XDG_CONFIG_HOME/dmux/dmuxrc

prefix=${PASSWORD_STORE_DIR-~/.password-store}
files=($prefix/**/*.gpg)
files=(${files[@]#"$prefix/"})
files=(${files[@]%.gpg})

item=$(print ${(F)files} | dmenu ${(z)DMENU_OPTS} -p "password" -sb "#702c2c" -sf "#e6dbdb")

if [[ -z "$item" ]]; then
    echo "No item loaded."
    exit
fi
pass show -c "$item"
if [[ $? == 0 ]] ; then
    notify-send -t 1500 -u low "Password loaded" $item
else
    notify-send -t 3000 -u critical "Password failed"
fi
