#!/bin/zsh

date=$(date +'%Y%m%d.%H%M%S')
localpath="$HOME/var/img/ss/dated"

mkdir -p $localpath
escrotum -s $localpath/$date.png

notify-send --expire-time 2 --category "screenshot" "Shot taken" "$date.png"
