#!/bin/zsh
# xrandr screen switch and rotator

other=$(xrandr | grep " connected (" | cut -d" " -f1)

if [[ "$other" == "eDP1" ]] ; then
    xrandr --output eDP1 --auto
    xrandr --output DP1 --off
else
    xrandr --output DP1 --auto
    xrandr --output eDP1 --off
fi

keyboard-setup
wp

killall keynav; keynav &> /dev/null &|
