#!/bin/zsh
# xrandr screen switch and rotator

out=$(xrandr)
other=$(echo $out | grep " connected (" | cut -d" " -f1)
current=$(echo $out | grep -e " connected [0-9]" | cut -d" " -f1)

if [[ -z "$other" ]]; then
  echo "No other non-disconnected screen. Doing nothing."
  exit 0
fi

xrandr --output $other --auto
xrandr --output $current --off

keyboard-setup
wp

killall keynav; keynav &> /dev/null &|
