#!/bin/zsh

setopt nullglob

clear
if (( $+commands[py.test] )); then
  opts=""


  # If there are toggle opts from vim, try to access them.
  dir="$PWD/.git/pytest-toggles"
  for file in $dir/* ; do
    t=$file:t
    if [[ $(wc -m $file | cut -d\  -f1) -gt 0 ]] ; then
      opts+=" --$t=$(<$file)"
    else
      if [[ $t =~ '^.$' ]]; then
        opts+=" -$t"
      else
        opts+=" --$t"
      fi
    fi
  done

  # If no other traceback reporting is set, use short
  if [[ ! -f $dir/tb ]] ; then
    opts+=" --tb=short"
  fi

  # If there is coverage and we can guess the source code dir, add coverage
  if [[ ! -f $dir/cov ]] && (( $+commands[coverage] )) && [[ -d $PWD/$PWD:t ]]; then
    opts+=" --cov=$PWD:t --cov-report=term-missing"
  fi

  py.test test ${(z)opts} --color=yes $@
else
  nosetests $@
fi
