#!/bin/zsh

if (( $+commands[py.test] )); then
  # If there is coverage and we can guess the source code dir, add coverage
  if (( $+commands[coverage] )) && [[ -d $PWD/$PWD:t ]]; then
    cov="--cov=$PWD:t"
  fi

  py.test test $cov $@
else
  nosetests $@
fi
