#!/bin/zsh

if [[ -n $(psg trayer) ]]; then
  killall trayer
else
  trayer --edge top --align right \
    --widthtype request --heighttype pixel --height 22 --expand true \
    --tint 0x222222 --transparent true --alpha 0 &|
fi
