#!/bin/zsh

pulseaudio-ctl $*
vol=$(pulseaudio-ctl full-status)
num=$(echo $vol | cut -d" " -f 1)

if [[ $(echo $vol | cut -d" " -f 2) == "yes" ]]; then
    notify-send "Volume" "Muted"
else
    notify-send "Volume" "${num}%"
fi
