#!/bin/zsh

if [[ $XORG_WM = 'hlwm' ]]; then
  winids=(${(f)"$(xwininfo -tree -root | grep $1 | tr -s ' ' | cut -d" " -f2)"})
  for winid in $winids ; do
    herbstclient raise $winid && herbstclient jumpto $winid
    if [[ $? == 0 ]] ; then
      break
    fi
  done
elif [[ $XORG_WM = 'i3' ]]; then
  # Use "title" as the default matcher, but provide for ability to change it
  # with $2.
  i3-msg "[${2:-title}=\"$1\"] focus" &> /dev/null
fi
