#!/usr/bin/env python3

import sys
import re
import shutil

from urllib.parse import quote
import subprocess as sub


def browser(url):
    sub.Popen(['browser', url], stdout=sub.PIPE, stderr=sub.PIPE)


def urlize(args):
    return quote(' '.join(args))


def google(args):
    return 'https://www.google.com/search?q=' + urlize(args)


def main():
    url = None

    if len(sys.argv) == 1:
        url = 'https://www.google.com'

    url = sys.argv[1]
    # If whatever was passed is an actual executable, execute it right away
    exe = shutil.which(url)
    if exe:
        sub.Popen([url], stdout=sub.PIPE, stderr=sub.PIPE)
        return 0

    if len(sys.argv) > 2 or len(sys.argv) == 2 and '.' not in sys.argv[1] \
            and not sys.argv[1].startswith('http'):
        url = google(sys.argv[1:])
    else:

        # If no protocol, add http
        if not re.search(r'[a-z]{2,}://', url):
            if 'spotify.net' in url:
                url = 'https://%s' % url
            else:
                url = 'http://%s' % url

    if url:
        browser(url)
        return 0
    else:
        print('Error: URL missing or malformed.')
        return 1

if __name__ == '__main__':
    sys.exit(main())
