setxkbmap a6 &
xset r rate 330 45 &

exec xsetroot -cursor_name left_ptr &
exec unclutter -idle 5 -root &
exec feh --bg-center ~/img/wp/scsw.jpg &

#exec wmii
#exec ratpoison -f ~/.config/ratpoison/ratpoisonrc
exec stumpwm
